//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelRFiD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.192.37.19:50000/XMII/SOAPRunner/RFID/TR_GET_MATERIAL_FROM_TAG2")]
        public string ModelRFiD_GET_MATERIAL_FROM_TAG2_XacuteWS {
            get {
                return ((string)(this["ModelRFiD_GET_MATERIAL_FROM_TAG2_XacuteWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.192.37.19:50000/XMII/SOAPRunner/RFID/TR_GET_MATERIAL_FROM_TAG")]
        public string ModelRFiD_GET_MATERIAL_FROM_TAG_XacuteWS {
            get {
                return ((string)(this["ModelRFiD_GET_MATERIAL_FROM_TAG_XacuteWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.192.37.19:50000/XMII/SOAPRunner/RFID/TR_GET_MATERIAL_FROM_MODEL")]
        public string ModelRFiD_GET_MATERIAL_FROM_MODEL_XacuteWS {
            get {
                return ((string)(this["ModelRFiD_GET_MATERIAL_FROM_MODEL_XacuteWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.192.37.19:50000/XMII/SOAPRunner/RFID/TR_RFID_LOGIN")]
        public string ModelRFiD_LOGIN_XacuteWS {
            get {
                return ((string)(this["ModelRFiD_LOGIN_XacuteWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.192.37.19:50000/XMII/SOAPRunner/RFID/TR_GET_MODEL_KONTROL_LIST")]
        public string ModelRFiD_GET_MODEL_KONTROL_LIST_XacuteWS {
            get {
                return ((string)(this["ModelRFiD_GET_MODEL_KONTROL_LIST_XacuteWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.192.37.19:50000/XMII/SOAPRunner/RFID/TR_SET_MODEL_KONTROL_LIST")]
        public string ModelRFiD_SET_MODEL_KONTROL_LIST_XacuteWS {
            get {
                return ((string)(this["ModelRFiD_SET_MODEL_KONTROL_LIST_XacuteWS"]));
            }
        }
    }
}
